version: '2'
services:

  influxdb:
    image: docker.io/bitnami/influxdb:1
    container_name: ftc-influxdb
    ports:
      - 8086:8086
      - 8088:8088
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=admin123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_ADMIN_RETENTION=0
    volumes:
      - ./data/influxdb:/bitnami/influxdb

  grafana:
    image: docker.io/bitnami/grafana:10
    container_name: ftc-grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_RENDERING_SERVER_URL=http://ftc-grafana-image-renderer:8080/render
      # - GF_RENDERING_CALLBACK_URL=http://ftc-grafana:3000/
    volumes:
      - ./data/grafana:/opt/bitnami/grafana/data

  # grafana-image-renderer:
  #   image: bitnami/grafana-image-renderer:1
  #   container_name: ftc-grafana-image-renderer
  #   ports:
  #     - 8080:8080
  #   environment:
  #     HTTP_HOST: "0.0.0.0"
  #     HTTP_PORT: "8080"
  #     ENABLE_METRICS: 'true'